### ISSUE TITLE
함수구현

### ISSUE THREAD

**Issue by HyeokyYun** [ParkSuah/2020OSS_team#10]
주말을 이용해서 필요한 함수들을 완성해봅시다.

**Comment by ParkSuah** [comment]
네 알겠습니다 !

**Comment by HyeokyYun** [comment]
이름으로 검색기능 추가했습니다

**Comment by ParkSuah** [comment]
점수로 검색기능 추가했습니다.

**Comment by ParkSuah** [comment]
등수별로 리스트 출력하도록 함수를 만들 때 구조체에 int rank가 필요할 것 같아서 추가했습니다
그리고 함수를 구현해봤는데 등수가 제대로 반영되지 않습니다..

**Comment by HyeokyYun** [comment]
등수가 이제 출력됩니다

**Comment by ParkSuah** [comment]
등수별로 나열하는 함수 구현 완료했습니다

**Comment by ParkSuah** [comment]
모든 데이터 한번에 삭제하기 구현했습니다

**Comment by HyeokyYun** [comment]
네네 알겠습니다! 수고하셨습니다
